import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/navbar/navbar";
import '../node_modules/@fortawesome/fontawesome-free/css/all.min.css'
import { Toaster } from "react-hot-toast"
import NextauthProvider from "./providers/nextauthProvider";
import Providers from "./providers/react-query-provider";
import Footer from './_components/footer/footer';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          {/* Navbar */}
          <Providers>
           <NextauthProvider>
             <Toaster />
          <Navbar/>
          <div className="h-[80px]"></div>
          <div className="container mx-auto max-w-7xl py-10">
            {children}
          </div>
          <Footer/>
           </NextauthProvider>
          </Providers>
      </body>
    </html>
  );
}
